
PACKAGECONFIG[ISPPipeline-accel] = "${RECIPE_SYSROOT}/usr/lib/libISPPipeline_accel.a,,ISPPipeline-accel,,"
PACKAGECONFIG[avbuf] = "${RECIPE_SYSROOT}/usr/lib/libavbuf.a,,avbuf,,"
PACKAGECONFIG[axipmon] = "${RECIPE_SYSROOT}/usr/lib/libaxipmon.a,,axipmon,,"
PACKAGECONFIG[axis-switch] = "${RECIPE_SYSROOT}/usr/lib/libaxis_switch.a,,axis-switch,,"
PACKAGECONFIG[axivdma] = "${RECIPE_SYSROOT}/usr/lib/libaxivdma.a,,axivdma,,"
PACKAGECONFIG[clockps] = "${RECIPE_SYSROOT}/usr/lib/libclockps.a,,clockps,,"
PACKAGECONFIG[common] = "${RECIPE_SYSROOT}/usr/lib/libcommon.a,,common,,"
PACKAGECONFIG[coresightps-dcc] = "${RECIPE_SYSROOT}/usr/lib/libcoresightps_dcc.a,,coresightps-dcc,,"
PACKAGECONFIG[csi] = "${RECIPE_SYSROOT}/usr/lib/libcsi.a,,csi,,"
PACKAGECONFIG[csudma] = "${RECIPE_SYSROOT}/usr/lib/libcsudma.a,,csudma,,"
PACKAGECONFIG[ddrcpsu] = "${RECIPE_SYSROOT}/usr/lib/libddrcpsu.a,,ddrcpsu,,"
PACKAGECONFIG[dpdma] = "${RECIPE_SYSROOT}/usr/lib/libdpdma.a,,dpdma,,"
PACKAGECONFIG[dphy] = "${RECIPE_SYSROOT}/usr/lib/libdphy.a,,dphy,,"
PACKAGECONFIG[dppsu] = "${RECIPE_SYSROOT}/usr/lib/libdppsu.a,,dppsu,,"
PACKAGECONFIG[emacps] = "${RECIPE_SYSROOT}/usr/lib/libemacps.a,,emacps,,"
PACKAGECONFIG[gpio] = "${RECIPE_SYSROOT}/usr/lib/libgpio.a,,gpio,,"
PACKAGECONFIG[gpiops] = "${RECIPE_SYSROOT}/usr/lib/libgpiops.a,,gpiops,,"
PACKAGECONFIG[iic] = "${RECIPE_SYSROOT}/usr/lib/libiic.a,,iic,,"
PACKAGECONFIG[iicps] = "${RECIPE_SYSROOT}/usr/lib/libiicps.a,,iicps,,"
PACKAGECONFIG[ipipsu] = "${RECIPE_SYSROOT}/usr/lib/libipipsu.a,,ipipsu,,"
PACKAGECONFIG[mipicsiss] = "${RECIPE_SYSROOT}/usr/lib/libmipicsiss.a,,mipicsiss,,"
PACKAGECONFIG[qspipsu] = "${RECIPE_SYSROOT}/usr/lib/libqspipsu.a,,qspipsu,,"
PACKAGECONFIG[resetps] = "${RECIPE_SYSROOT}/usr/lib/libresetps.a,,resetps,,"
PACKAGECONFIG[rtcpsu] = "${RECIPE_SYSROOT}/usr/lib/librtcpsu.a,,rtcpsu,,"
PACKAGECONFIG[scugic] = "${RECIPE_SYSROOT}/usr/lib/libscugic.a,,scugic,,"
PACKAGECONFIG[sdps] = "${RECIPE_SYSROOT}/usr/lib/libsdps.a,,sdps,,"
PACKAGECONFIG[spips] = "${RECIPE_SYSROOT}/usr/lib/libspips.a,,spips,,"
PACKAGECONFIG[sysmonpsu] = "${RECIPE_SYSROOT}/usr/lib/libsysmonpsu.a,,sysmonpsu,,"
PACKAGECONFIG[ttcps] = "${RECIPE_SYSROOT}/usr/lib/libttcps.a,,ttcps,,"
PACKAGECONFIG[uartps] = "${RECIPE_SYSROOT}/usr/lib/libuartps.a,,uartps,,"
PACKAGECONFIG[usbpsu] = "${RECIPE_SYSROOT}/usr/lib/libusbpsu.a,,usbpsu,,"
PACKAGECONFIG[v-csc] = "${RECIPE_SYSROOT}/usr/lib/libv_csc.a,,v-csc,,"
PACKAGECONFIG[v-deinterlacer] = "${RECIPE_SYSROOT}/usr/lib/libv_deinterlacer.a,,v-deinterlacer,,"
PACKAGECONFIG[v-frmbuf-wr] = "${RECIPE_SYSROOT}/usr/lib/libv_frmbuf_wr.a,,v-frmbuf-wr,,"
PACKAGECONFIG[v-hcresampler] = "${RECIPE_SYSROOT}/usr/lib/libv_hcresampler.a,,v-hcresampler,,"
PACKAGECONFIG[v-hscaler] = "${RECIPE_SYSROOT}/usr/lib/libv_hscaler.a,,v-hscaler,,"
PACKAGECONFIG[v-letterbox] = "${RECIPE_SYSROOT}/usr/lib/libv_letterbox.a,,v-letterbox,,"
PACKAGECONFIG[v-vcresampler] = "${RECIPE_SYSROOT}/usr/lib/libv_vcresampler.a,,v-vcresampler,,"
PACKAGECONFIG[v-vscaler] = "${RECIPE_SYSROOT}/usr/lib/libv_vscaler.a,,v-vscaler,,"
PACKAGECONFIG[video-common] = "${RECIPE_SYSROOT}/usr/lib/libvideo_common.a,,video-common,,"
PACKAGECONFIG[vprocss] = "${RECIPE_SYSROOT}/usr/lib/libvprocss.a,,vprocss,,"
PACKAGECONFIG[wdtps] = "${RECIPE_SYSROOT}/usr/lib/libwdtps.a,,wdtps,,"
PACKAGECONFIG[zdma] = "${RECIPE_SYSROOT}/usr/lib/libzdma.a,,zdma,,"