set(DRIVER_INSTANCES "ISPPipeline_accel@b0000000")
set(DRIVER_PROP_0_LIST "xlnx,ISPPipeline-accel-1.0;0xb0000000")
set(DRIVER_OPTPROP_0_LIST "")
list(APPEND TOTAL_DRIVER_PROP_LIST DRIVER_PROP_0_LIST)
