set(DRIVER_INSTANCES "capture_pipeline_isp_mipi_csi2_rx_subsyst_0_rx@0;capture_pipeline_raspi_mipi_csi2_rx_subsyst_0_rx@0")
set(DRIVER_PROP_0_LIST "xlnx,mipi-csi2-rx-ctrl-1.0;0x0;0x4;0x0;0x0;0x0;0x0")
set(DRIVER_OPTPROP_0_LIST "")
list(APPEND TOTAL_DRIVER_PROP_LIST DRIVER_PROP_0_LIST)
set(DRIVER_PROP_1_LIST "xlnx,mipi-csi2-rx-ctrl-1.0;0x0;0x2;0x0;0x1;0x0;0x0")
set(DRIVER_OPTPROP_1_LIST "")
list(APPEND TOTAL_DRIVER_PROP_LIST DRIVER_PROP_1_LIST)
